version: "3.9"

services:
  database_desafio: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: desafio
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local